force-app/queue-bot/default/objects/Queue__c/Queue__c.object-meta.xml
<CustomObject>
    <label>Queue</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/queue-bot/default/objects/Queue__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/queue-bot/default/objects/Queue__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Queues</relationshipLabel>
    <relationshipName>Queues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/queue-bot/default/objects/Queue_Member__c/Queue_Member__c.object-meta.xml
<CustomObject>
    <label>Queue Member</label>
    <nameField>
        <label>Queue Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queue Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/queue-bot/default/objects/Queue_Member__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <label>Place</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/queue-bot/default/objects/Queue_Member__c/fields/Queue__c.field-meta.xml
<CustomField>
    <fullName>Queue__c</fullName>
    <label>Queue</label>
    <referenceTo>Queue__c</referenceTo>
    <relationshipLabel>Queue Members</relationshipLabel>
    <relationshipName>Queue_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/queue-bot/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/queue-bot/default/classes/commands/ShowQueueCommand.cls
/**
 * Created by Ilya Matsuev on 9/12/2020.
 */

public with sharing class ShowQueueCommand implements IBotCommand {

    public String answer(Map<String, String> messageInfo) {
        List<Queue__c> queues = QueueService.getRecentQueues();
        String answer = '';
        for (Queue__c queue: queues) {
            answer += queue.Subject__r.Name + ' - ' + queue.Scheduled_Date__c + '\n';
            for (Queue_Member__c member : queue.Queue_Members__r) {
                answer += member.Place__c + '. ' + member.Name + '\n';
            }
            answer += '\n';
        }
        if (queues.isEmpty()) {
            answer = 'There are no queues scheduled for tomorrow';
        }
        return answer;
    }
}