force-app/queue-bot/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/queue-bot/default/objects/Sub_Group__c/Sub_Group__c.object-meta.xml
<CustomObject>
    <label>Sub-Group</label>
    <nameField>
        <label>Sub Groups Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/queue-bot/default/objects/Sub_Group__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Sub-Groups</relationshipLabel>
    <relationshipName>Sub_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/queue-bot/default/objects/Sub_Group__c/fields/Sub_Group_Password__c.field-meta.xml
<CustomField>
    <fullName>Sub_Group_Password__c</fullName>
    <label>Sub-Group Password</label>
    <length>80</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/queue-bot/default/classes/commands/JoinSubGroupCommand.cls
/**
 * Created by Ilya Matsuev on 9/12/2020.
 */

public with sharing class JoinSubGroupCommand implements IBotCommand {

    private final List<String> COMMAND_ARGS_NAMES = new List<String> {
            'commandName',
            'groupName',
            'subGroupName',
            'password'
    };

    public String answer(Map<String, String> messageInfo) {
        String answer = '';
        Map<String, String> args = ArgumentsParser.parseCommandArgs(messageInfo.get('message'), COMMAND_ARGS_NAMES);
        Sub_Group__c subGroup = GroupService.getSubGroupByName(args.get('groupName'), args.get('subGroupName'));
        if (subGroup == null || subGroup.Sub_Group_Password__c != args.get('password')) {
            answer = 'Invalid group/sub-group name or the password is wrong';
        } else if (GroupService.alreadyJoined(subGroup, messageInfo.get('userId'))) {
            answer = 'You have been already joined the ' + subGroup.Name + ' sub-group of a ' + subGroup.Group__r.Name + ' group';
        } else {
            GroupService.joinGroup(subGroup, messageInfo.get('userId'), messageInfo.get('name'));
            answer = 'You have successfully joined the ' + subGroup.Name + ' sub-group of a ' + subGroup.Group__r.Name + ' group';
        }
        return answer;
    }
}