force-app/queue-bot/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/queue-bot/default/objects/Group_Member__c/Group_Member__c.object-meta.xml
<CustomObject>
    <label>Group Member</label>
    <nameField>
        <label>Group Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/queue-bot/default/objects/Group_Member__c/fields/Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Sub_Group__c</fullName>
    <label>Sub-Group</label>
    <referenceTo>Sub_Group__c</referenceTo>
    <relationshipLabel>Group Members</relationshipLabel>
    <relationshipName>Group_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/queue-bot/default/objects/Group_Member__c/fields/Telegram_Username__c.field-meta.xml
<CustomField>
    <fullName>Telegram_Username__c</fullName>
    <label>Telegram Username</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/queue-bot/default/objects/Group_Member__c/fields/VK_Username__c.field-meta.xml
<CustomField>
    <fullName>VK_Username__c</fullName>
    <label>VK Username</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/queue-bot/default/objects/Sub_Group__c/Sub_Group__c.object-meta.xml
<CustomObject>
    <label>Sub-Group</label>
    <nameField>
        <label>Sub Groups Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/queue-bot/default/objects/Sub_Group__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Sub-Groups</relationshipLabel>
    <relationshipName>Sub_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/queue-bot/default/objects/Sub_Group__c/fields/Sub_Group_Password__c.field-meta.xml
<CustomField>
    <fullName>Sub_Group_Password__c</fullName>
    <label>Sub-Group Password</label>
    <length>80</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/queue-bot/default/classes/services/GroupService.cls
/**
 * Created by Ilya Matsuev on 9/6/2020.
 */

public with sharing class GroupService {

    private static final Map<String, Group_Member__c> CASHED_MEMBERS_MAP = new Map<String, Group_Member__c>();


    public static Group_Member__c getMemberByUserId(String userId) {
        Group_Member__c member = CASHED_MEMBERS_MAP.get(userId);
        if (member == null) {
            List<Group_Member__c> members = [
                    SELECT Id, Name, Sub_Group__c
                    FROM Group_Member__c
                    WHERE Telegram_Username__c = :userId
                    OR VK_Username__c = :userId
                    LIMIT 1
            ];
            if (!members.isEmpty()) {
                member = members.get(0);
                CASHED_MEMBERS_MAP.put(userId, member);
            }
        }
        return member;
    }

    public static Sub_Group__c getSubGroupByName(String groupName, String subGroupName) {
        List<Sub_Group__c> subGroups = [
                SELECT Name, Sub_Group_Password__c, Group__r.Name
                FROM Sub_Group__c
                WHERE Group__r.Name = :groupName
                AND Name = :subGroupName
                LIMIT 1
        ];
        Sub_Group__c subGroup = null;
        if (!subGroups.isEmpty()) {
            subGroup = subGroups.get(0);
        }
        return subGroup;
    }

    public static Boolean alreadyJoined(Sub_Group__c subGroup, String userId) {
        Boolean hasSuchGroupMember = [
                SELECT COUNT()
                FROM Group_Member__c
                WHERE Sub_Group__c = :subGroup.Id
                AND (Telegram_Username__c = :userId OR VK_Username__c = :userId)
        ] > 0;
        return hasSuchGroupMember;
    }

    public static Group_Member__c joinGroup(Sub_Group__c subGroup, String userId, String name) {
        Group_Member__c newMember = new Group_Member__c(
                Name = name,
                Sub_Group__c = subGroup.Id
        );
        if (BotCommandManager.commandContext == BotCommandContext.TELEGRAM) {
            newMember.Telegram_Username__c = userId;
        } else if (BotCommandManager.commandContext == BotCommandContext.VK) {
            newMember.VK_Username__c = userId;
        }
        insert newMember;
        return newMember;
    }
}