force-app/queue-bot/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/queue-bot/default/objects/Group_Member__c/Group_Member__c.object-meta.xml
<CustomObject>
    <label>Group Member</label>
    <nameField>
        <label>Group Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/queue-bot/default/objects/Group_Member__c/fields/Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Sub_Group__c</fullName>
    <label>Sub-Group</label>
    <referenceTo>Sub_Group__c</referenceTo>
    <relationshipLabel>Group Members</relationshipLabel>
    <relationshipName>Group_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/queue-bot/default/objects/Queue__c/Queue__c.object-meta.xml
<CustomObject>
    <label>Queue</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/queue-bot/default/objects/Queue__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/queue-bot/default/objects/Queue__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Queues</relationshipLabel>
    <relationshipName>Queues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/queue-bot/default/objects/Sub_Group__c/Sub_Group__c.object-meta.xml
<CustomObject>
    <label>Sub-Group</label>
    <nameField>
        <label>Sub Groups Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/queue-bot/default/objects/Sub_Group__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Sub-Groups</relationshipLabel>
    <relationshipName>Sub_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/queue-bot/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

scripts/apex/init-groups.cls
delete [SELECT Id FROM Group__c];
delete [SELECT Id FROM Sub_Group__c];
delete [SELECT Id FROM Group_Member__c];

Group__c fourth = new Group__c(Name = 'FIT-4-4');
insert fourth;
Sub_Group__c firstSubGroup = new Sub_Group__c(Name = '1', Group__c = fourth.Id);
Sub_Group__c secondSubGroup = new Sub_Group__c(Name = '2', Group__c = fourth.Id);
insert new Sub_Group__c[] {firstSubGroup, secondSubGroup};

List<Group_Member__c> members = new List<Group_Member__c> {
        new Group_Member__c(Name = 'Илья Мацуев', Sub_Group__c = firstSubGroup.Id),
        new Group_Member__c(Name = 'Илья Сикорский', Sub_Group__c = firstSubGroup.Id),
        new Group_Member__c(Name = 'Сергей Жугин', Sub_Group__c = firstSubGroup.Id),
        new Group_Member__c(Name = 'Егор Гончар', Sub_Group__c = firstSubGroup.Id),
        new Group_Member__c(Name = 'Роман Кукла', Sub_Group__c = firstSubGroup.Id),
        new Group_Member__c(Name = 'Кирилл Кутас', Sub_Group__c = firstSubGroup.Id),
        new Group_Member__c(Name = 'Костя Ширитон', Sub_Group__c = firstSubGroup.Id),
        new Group_Member__c(Name = 'Swatar Common', Sub_Group__c = firstSubGroup.Id),
        new Group_Member__c(Name = 'Артемий Марковский', Sub_Group__c = firstSubGroup.Id),
        new Group_Member__c(Name = 'Александр Фомин', Sub_Group__c = firstSubGroup.Id),
        new Group_Member__c(Name = 'Елизавета Бородина', Sub_Group__c = firstSubGroup.Id),
        new Group_Member__c(Name = 'Юра Карленок', Sub_Group__c = firstSubGroup.Id),
        new Group_Member__c(Name = 'Екатерина Петрович', Sub_Group__c = firstSubGroup.Id),
        new Group_Member__c(Name = 'Валентин Дубалеко', Sub_Group__c = firstSubGroup.Id)
};
insert members;

List<Subject__c> subjects = new List<Subject__c> {
        new Subject__c(Name = '.net'),
        new Subject__c(Name = 'java')
};
insert subjects;
List<Queue__c> queuesMonday = new List<Queue__c>();
Datetime startClassesDate = Datetime.newInstance(2020, 9, 7, 8, 0, 0);
for (Subject__c subject: subjects) {
    queuesMonday.add(new Queue__c(
            Name = String.valueOf(startClassesDate.date()) + '-' + subject.Name,
            Scheduled_Date__c = startClassesDate,
            Subject__c = subject.Id
    ));
    startClassesDate = startClassesDate.addMinutes(110);
}
insert queuesMonday;